// <auto-generated />
using System;
using DitibStasbourg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DitibStasbourg.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622203910_AddMaliyeAndGorevliMetadata")]
    partial class AddMaliyeAndGorevliMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DitibStasbourg.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Dashboard.DashboardPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ShowAssignmentChart")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowKurbanChart")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPersonnelChart")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowRegionMap")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("DashboardPreferences");
                });

            modelBuilder.Entity("DitibStasbourg.Models.DatabaseAuditLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DatabaseAuditLogs");
                });

            modelBuilder.Entity("DitibStasbourg.Models.DernekUye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AileUyeSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Iletisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KurumId");

                    b.ToTable("DernekUyeleri");
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GorevliId")
                        .HasColumnType("int");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<int?>("YerineGelenGorevliId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevliId");

                    b.HasIndex("KurumId");

                    b.HasIndex("YerineGelenGorevliId");

                    b.ToTable("GorevGecmisleri");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Gorevlendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GorevliId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YerineGelecekGorevliId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("YerineGelisPlanlananBitisTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YerineGelisPlanlananTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevliId");

                    b.HasIndex("KurumId");

                    b.HasIndex("YerineGelecekGorevliId");

                    b.HasIndex("Tarih", "BitisTarihi", "KurumId", "GorevliId")
                        .HasDatabaseName("IX_Gorevlendirme_Filters");

                    b.ToTable("Gorevlendirme");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaslangicTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GorevliId = 1,
                            IsActive = false,
                            IsDeleted = false,
                            KurumId = 1,
                            Tarih = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BaslangicTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GorevliId = 2,
                            IsActive = false,
                            IsDeleted = false,
                            KurumId = 2,
                            Tarih = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BaslangicTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GorevliId = 3,
                            IsActive = false,
                            IsDeleted = false,
                            KurumId = 3,
                            Tarih = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevlendirmeNot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GorevlendirmeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NotIcerik")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("YazanKisiId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GorevlendirmeId");

                    b.HasIndex("YazanKisiId");

                    b.ToTable("GorevlendirmeNotlari");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Gorevli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AnneAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AskerlikDurumuId")
                        .HasColumnType("int");

                    b.Property<string>("BabaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BasvuruTuruId")
                        .HasColumnType("int");

                    b.Property<string>("CepTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Derece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DiyanetGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("EgitimDurumuId")
                        .HasColumnType("int");

                    b.Property<string>("EgitimKursBelgeleri")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EmeklilikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EsDurumu")
                        .HasColumnType("int");

                    b.Property<string>("EvTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotografYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GorevUzatmaBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GorevliDurumId")
                        .HasColumnType("int");

                    b.Property<int?>("HafizlikDurumuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IlkGoreveBaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kademe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KadroTuruId")
                        .HasColumnType("int");

                    b.Property<int?>("KanGrubuId")
                        .HasColumnType("int");

                    b.Property<string>("LinkedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memleketi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MezuniyetBolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MezuniyetOkul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasaportNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PasaportTuru")
                        .HasColumnType("int");

                    b.Property<string>("SicilNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SozlesmeTipId")
                        .HasColumnType("int");

                    b.Property<string>("TCKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("UnvanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AskerlikDurumuId");

                    b.HasIndex("BasvuruTuruId");

                    b.HasIndex("EgitimDurumuId");

                    b.HasIndex("GorevliDurumId");

                    b.HasIndex("HafizlikDurumuId");

                    b.HasIndex("KadroTuruId");

                    b.HasIndex("KanGrubuId");

                    b.HasIndex("SicilNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Gorevli_SicilNo")
                        .HasFilter("[SicilNo] IS NOT NULL");

                    b.HasIndex("SozlesmeTipId");

                    b.HasIndex("TCKimlikNo")
                        .IsUnique()
                        .HasFilter("[TCKimlikNo] IS NOT NULL");

                    b.HasIndex("UnvanId");

                    b.HasIndex("Ad", "Soyad", "Email")
                        .HasDatabaseName("IX_Gorevli_Search");

                    b.ToTable("Gorevli");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ahmet",
                            Durum = 0,
                            Email = "ahmet.yilmaz@example.com",
                            IsDeleted = false,
                            Soyad = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Mehmet",
                            Durum = 0,
                            Email = "mehmet.demir@example.com",
                            IsDeleted = false,
                            Soyad = "Demir"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Ayşe",
                            Durum = 0,
                            Email = "ayse.kaya@example.com",
                            IsDeleted = false,
                            Soyad = "Kaya"
                        });
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevliFaaliyetRaporu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaaliyetDetayi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GorevliId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KatilimciSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KursTuru")
                        .HasColumnType("int");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RaporTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevliId");

                    b.HasIndex("KurumId");

                    b.ToTable("GorevliFaaliyetRaporlari");
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevliIzin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GorevliId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IzinAdresi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IzinTelefonu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IzinTuru")
                        .HasColumnType("int");

                    b.Property<int>("OnayDurumu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OnaylayanKisi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GorevliId");

                    b.ToTable("GorevliIzinler");
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevliNot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GorevliId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NotIcerik")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("YazanKisiId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GorevliId");

                    b.HasIndex("YazanKisiId");

                    b.ToTable("GorevliNotlari");
                });

            modelBuilder.Entity("DitibStasbourg.Models.HelpTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RequiredClaim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HelpTopics");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Hissedar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVekaletTaken")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KurbanlikId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KurbanlikId");

                    b.ToTable("Hissedarlar");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Kurbanlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RemainingShares")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalShares")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Kurbanliklar");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Kurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("BaskanMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaskonsoloslukBolgesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolge")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CemaatCount")
                        .HasColumnType("int");

                    b.Property<string>("CrmUyelikFormDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DernekBaskaniAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DernekBaskaniIletisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinGorevlisiAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinGorevlisiIletisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkonomiNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenchRegistrationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IletisimNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurulusKanunu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Maili")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RnaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SiretNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int?>("UstKurumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UstKurumId");

                    b.HasIndex("Bolge", "Sehir")
                        .HasDatabaseName("IX_Kurum_Geo");

                    b.ToTable("Kurum");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adres = "12 Rue de la Musau",
                            AktifMi = true,
                            IbanNo = "",
                            IsDeleted = false,
                            Isim = "Strasbourg Yunus Emre Camii",
                            Latitude = 48.566099999999999,
                            Longitude = 7.7786,
                            RnaNo = "",
                            Sehir = "Strasbourg",
                            SiretNo = "",
                            Tip = 0
                        },
                        new
                        {
                            Id = 2,
                            Adres = "3 Rue des Écoles",
                            AktifMi = true,
                            IbanNo = "",
                            IsDeleted = false,
                            Isim = "Bischheim Fatih Camii",
                            Latitude = 48.6143,
                            Longitude = 7.7491000000000003,
                            RnaNo = "",
                            Sehir = "Bischheim",
                            SiretNo = "",
                            Tip = 0
                        },
                        new
                        {
                            Id = 3,
                            Adres = "5 Place Kléber",
                            AktifMi = true,
                            IbanNo = "",
                            IsDeleted = false,
                            Isim = "Strasbourg Türk Kültür Derneği",
                            Latitude = 48.582999999999998,
                            Longitude = 7.7477999999999998,
                            RnaNo = "",
                            Sehir = "Strasbourg",
                            SiretNo = "",
                            Tip = 1
                        });
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumButce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DernekContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DitibContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KurumId");

                    b.ToTable("KurumButceler");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumButcePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("KurumButceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("ScheduledAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionTutanakNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KurumButceId");

                    b.ToTable("KurumButcePeriods");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumFinansalDonem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignType")
                        .HasColumnType("int");

                    b.Property<decimal>("CollectedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KurumId");

                    b.ToTable("KurumFinansalDonemler");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumHavuzTakibi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("bit");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonnelGender")
                        .HasColumnType("int");

                    b.Property<decimal>("VariableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KurumId");

                    b.ToTable("KurumHavuzTakibiSet");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumKasaOdenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationType")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IslemYapan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetGorevliId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TutanakNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("KurumId");

                    b.HasIndex("TargetGorevliId");

                    b.ToTable("KurumKasaOdenekler");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumYonetimKuruluUyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<int>("YonetimRolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KurumId");

                    b.HasIndex("YonetimRolId");

                    b.ToTable("KurumYonetimKuruluUyeleri");
                });

            modelBuilder.Entity("DitibStasbourg.Models.LookupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LookupTypes");
                });

            modelBuilder.Entity("DitibStasbourg.Models.LookupValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LookupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LookupTypeId");

                    b.ToTable("LookupValues");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_AskerlikDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_AskerlikDurumlari");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_EgitimDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_EgitimDurumlari");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_GorevliDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ref_GorevliDurums");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_HafizlikDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_HafizlikDurumlari");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_KadroTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_KadroTurleri");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_KanGrubu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_KanGruplari");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_KurumTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_KurumTurus");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_SozlesmeTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_SozlesmeTips");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_Unvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_Unvans");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Ref_YonetimRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Ref_YonetimRols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Başkan",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Sekreter",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Muhasip",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Üye",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("DitibStasbourg.Models.Security.RoleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RoleTemplates");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Security.RoleTemplateClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleTemplateId");

                    b.ToTable("RoleTemplateClaims");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Security.UserClaimOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDenied")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaimOverrides");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Security.UserRoleTemplate", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleTemplateId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleTemplateId");

                    b.ToTable("UserRoleTemplates");
                });

            modelBuilder.Entity("DitibStasbourg.Models.SystemAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DitibStasbourg.Models.DernekUye", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany("DernekUyeleri")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevGecmisi", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Gorevli", "Gorevli")
                        .WithMany("GorevGecmisleri")
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany()
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DitibStasbourg.Models.Gorevli", "YerineGelenGorevli")
                        .WithMany()
                        .HasForeignKey("YerineGelenGorevliId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gorevli");

                    b.Navigation("Kurum");

                    b.Navigation("YerineGelenGorevli");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Gorevlendirme", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Gorevli", "Gorevli")
                        .WithMany("Gorevlendirmeler")
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany("Gorevlendirmeler")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DitibStasbourg.Models.Gorevli", "YerineGelecekGorevli")
                        .WithMany()
                        .HasForeignKey("YerineGelecekGorevliId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gorevli");

                    b.Navigation("Kurum");

                    b.Navigation("YerineGelecekGorevli");
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevlendirmeNot", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Gorevlendirme", "Gorevlendirme")
                        .WithMany("GorevlendirmeNotlari")
                        .HasForeignKey("GorevlendirmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "YazanKisi")
                        .WithMany()
                        .HasForeignKey("YazanKisiId");

                    b.Navigation("Gorevlendirme");

                    b.Navigation("YazanKisi");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Gorevli", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Ref_AskerlikDurumu", "AskerlikDurumu")
                        .WithMany()
                        .HasForeignKey("AskerlikDurumuId");

                    b.HasOne("DitibStasbourg.Models.LookupValue", "BasvuruTuru")
                        .WithMany()
                        .HasForeignKey("BasvuruTuruId");

                    b.HasOne("DitibStasbourg.Models.Ref_EgitimDurumu", "EgitimDurumu")
                        .WithMany()
                        .HasForeignKey("EgitimDurumuId");

                    b.HasOne("DitibStasbourg.Models.Ref_GorevliDurum", "GorevliDurumBilgisi")
                        .WithMany()
                        .HasForeignKey("GorevliDurumId");

                    b.HasOne("DitibStasbourg.Models.Ref_HafizlikDurumu", "HafizlikDurumu")
                        .WithMany()
                        .HasForeignKey("HafizlikDurumuId");

                    b.HasOne("DitibStasbourg.Models.Ref_KadroTuru", "KadroTuru")
                        .WithMany()
                        .HasForeignKey("KadroTuruId");

                    b.HasOne("DitibStasbourg.Models.Ref_KanGrubu", "KanGrubu")
                        .WithMany()
                        .HasForeignKey("KanGrubuId");

                    b.HasOne("DitibStasbourg.Models.Ref_SozlesmeTip", "SozlesmeTip")
                        .WithMany()
                        .HasForeignKey("SozlesmeTipId");

                    b.HasOne("DitibStasbourg.Models.Ref_Unvan", "Unvan")
                        .WithMany()
                        .HasForeignKey("UnvanId");

                    b.Navigation("AskerlikDurumu");

                    b.Navigation("BasvuruTuru");

                    b.Navigation("EgitimDurumu");

                    b.Navigation("GorevliDurumBilgisi");

                    b.Navigation("HafizlikDurumu");

                    b.Navigation("KadroTuru");

                    b.Navigation("KanGrubu");

                    b.Navigation("SozlesmeTip");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevliFaaliyetRaporu", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Gorevli", "Gorevli")
                        .WithMany("FaaliyetRaporlari")
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany()
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gorevli");

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevliIzin", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Gorevli", "Gorevli")
                        .WithMany("Izinler")
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gorevli");
                });

            modelBuilder.Entity("DitibStasbourg.Models.GorevliNot", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Gorevli", "Gorevli")
                        .WithMany("GorevliNotlari")
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "YazanKisi")
                        .WithMany()
                        .HasForeignKey("YazanKisiId");

                    b.Navigation("Gorevli");

                    b.Navigation("YazanKisi");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Hissedar", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Kurbanlik", "Kurbanlik")
                        .WithMany("Hissedarlar")
                        .HasForeignKey("KurbanlikId");

                    b.Navigation("Kurbanlik");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Kurum", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Ref_KurumTuru", "UstKurum")
                        .WithMany()
                        .HasForeignKey("UstKurumId");

                    b.Navigation("UstKurum");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumButce", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany("Butceler")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumButcePeriod", b =>
                {
                    b.HasOne("DitibStasbourg.Models.KurumButce", "KurumButce")
                        .WithMany("Periods")
                        .HasForeignKey("KurumButceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KurumButce");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumFinansalDonem", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany("FinansalDonemler")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumHavuzTakibi", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany("HavuzTakibi")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumKasaOdenek", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany()
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DitibStasbourg.Models.Gorevli", "TargetGorevli")
                        .WithMany()
                        .HasForeignKey("TargetGorevliId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kurum");

                    b.Navigation("TargetGorevli");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumYonetimKuruluUyesi", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Kurum", "Kurum")
                        .WithMany("YonetimKuruluUyeleri")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DitibStasbourg.Models.Ref_YonetimRol", "YonetimRol")
                        .WithMany()
                        .HasForeignKey("YonetimRolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kurum");

                    b.Navigation("YonetimRol");
                });

            modelBuilder.Entity("DitibStasbourg.Models.LookupValue", b =>
                {
                    b.HasOne("DitibStasbourg.Models.LookupType", "LookupType")
                        .WithMany("Values")
                        .HasForeignKey("LookupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupType");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Security.RoleTemplateClaim", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Security.RoleTemplate", "RoleTemplate")
                        .WithMany("Claims")
                        .HasForeignKey("RoleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleTemplate");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Security.UserRoleTemplate", b =>
                {
                    b.HasOne("DitibStasbourg.Models.Security.RoleTemplate", "RoleTemplate")
                        .WithMany()
                        .HasForeignKey("RoleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleTemplate");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DitibStasbourg.Models.Gorevlendirme", b =>
                {
                    b.Navigation("GorevlendirmeNotlari");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Gorevli", b =>
                {
                    b.Navigation("FaaliyetRaporlari");

                    b.Navigation("GorevGecmisleri");

                    b.Navigation("Gorevlendirmeler");

                    b.Navigation("GorevliNotlari");

                    b.Navigation("Izinler");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Kurbanlik", b =>
                {
                    b.Navigation("Hissedarlar");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Kurum", b =>
                {
                    b.Navigation("Butceler");

                    b.Navigation("DernekUyeleri");

                    b.Navigation("FinansalDonemler");

                    b.Navigation("Gorevlendirmeler");

                    b.Navigation("HavuzTakibi");

                    b.Navigation("YonetimKuruluUyeleri");
                });

            modelBuilder.Entity("DitibStasbourg.Models.KurumButce", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("DitibStasbourg.Models.LookupType", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("DitibStasbourg.Models.Security.RoleTemplate", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
